============================= test session starts ==============================
platform linux -- Python 3.13.7, pytest-8.3.3, pluggy-1.5.0
rootdir: /home/bcorfman/dev/arcade_actions
configfile: pyproject.toml
plugins: cov-6.0.0
collected 39 items

tests/test_pattern.py .......................................            [100%]

---------- coverage: platform linux, python 3.13.7-final-0 -----------
Name                 Stmts   Miss  Cover   Missing
--------------------------------------------------
actions/pattern.py     541    322    40%   42, 44, 135, 137, 187, 261, 278-282, 315, 339-341, 365, 386-388, 418, 487, 489, 493, 500, 581, 583, 609-620, 625-653, 658-667, 672-682, 687-697, 738-843, 847-876, 887-942, 958-983, 1009-1159, 1175-1236
--------------------------------------------------
TOTAL                  541    322    40%


============================== 39 passed in 1.46s ==============================
Exception ignored in atexit callback <function _delete_audio_driver at 0x771715ea0220>:
Traceback (most recent call last):
  File "/home/bcorfman/dev/arcade_actions/.venv/lib/python3.13/site-packages/pyglet/media/drivers/__init__.py", line 80, in _delete_audio_driver
    for p in Source._players:
AttributeError: type object 'Source' has no attribute '_players'
